### PR TITLE
Add option "forceCopyTemplates"

### PR DESCRIPTION
**Pull request by Rapha149**
I added an option "forceCopyTemplates" which enables copying templates for static servers. If the option is enabled, everything inside the template and parent templates of the group will be copied to the static server before starting. This does not mean that the other files will be deleted - it just means that the files that are present in the template will be replaced.

### CODE REVIEW

**Review by FllipEis — CHANGES_REQUESTED** [review]
Looks good, but you have to add a `VersionConverter` (named `Converter_2_5_To_2_6`), because it could break the whole system without one.

Here is a out [last converter](https://github.com/theSimpleCloud/SimpleCloud/blob/b1fca9652887002454bf8733db7844f79a105c0f/simplecloud-base/src/main/kotlin/eu/thesimplecloud/base/manager/update/converter/Converter_2_4_To_2_5.kt) as example. Yours should update every existing group file and add the new parameter to the config. The converter needs to be registered in the [VersionConversionManager](https://github.com/theSimpleCloud/SimpleCloud/blob/b1fca9652887002454bf8733db7844f79a105c0f/simplecloud-base/src/main/kotlin/eu/thesimplecloud/base/manager/update/converter/VersionConversionManager.kt#L42).

**Comment by Rapha149** [comment]
What exactly should I put inside the `convert` method? Because the line with the option gets automatically added to the group json files. Or should I "manually" add it in the `convert` method for every group file?

**Comment by FllipEis** [comment]
> Because the line with the option gets automatically added to the group json files

Have you tested this? I thought that this won't work.

**Comment by Rapha149** [comment]
Yes I tested it. The line gets automatically added. I think it's because when it isn't found in the json file it just assumes `false` for a default value and then when saving the file it gets added.

**Comment by FllipEis** [comment]
Thanks, I will merge this then! 👍

**Review by FllipEis — APPROVED** [review]

**Pull request merged**
